import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import Logo from "./assets/logo";
import Ilustration from "./assets/ilustration";

const nunitoSans = Nunito_Sans({
	variable: "--font-nunito-sans",
	subsets: ["latin"],
	weight: ["200", "300", "400", "500", "600", "700", "800", "900", "1000"],
});

export const metadata: Metadata = {
	title: "Workplace",
	description: "Generated by workplace",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={nunitoSans.className}
			>
				<div className="bg-[#f4f9fd] antialiased  w-screen h-screen px-10 pt-5 pb-[30px]">
					<div className="flex  w-full h-full  rounded-3xl overflow-hidden  bg-white">
						<div className="bg-[#3f8cff] h-full flex-1/2 flex flex-col gap-[48px] justify-center  py-[60px] px-[94px]">
							<header className="flex gap-[30px] items-center">
								<Logo />
								<div className="text-white text-3xl font-bold ">Woorkroom</div>
							</header>

							<section className="flex gap-[30px] items-center flex-col">
								<div className="text-white text-4xl font-bold  w-full pl-24 leading-[56px]">
									Seu lugar para trabalhar
									<br />
									Plano. Criar. Controlar.
								</div>
								<Ilustration />
							</section>
						</div>
						<div className="flex-1/2 h-full">{children}</div>
					</div>
				</div>
			</body>
		</html>
	);
}
